# Generated by Django 6.0.5 on 2026-05-28 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCNI', models.CharField(max_length=50, unique=True)),
                ('numeroEtud', models.IntegerField(unique=True)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('solde_portefeuille', models.IntegerField(default=0)),
                ('tickets_petitDej', models.IntegerField(default=0)),
                ('tickets_repas', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('petitDej', 'Petit Déjeuner'), ('repas', 'Repas')], max_length=20)),
                ('nombre', models.IntegerField(default=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='tickets.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Debiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('controleur', models.ForeignKey(limit_choices_to={'profil__role': 'controleur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitDej', models.IntegerField(default=0)),
                ('repas', models.IntegerField(default=0)),
                ('montant_total', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='tickets.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('vendeur', 'Vendeur / Caissier'), ('controleur', 'Contrôleur / Portier'), ('administrateur', 'Administrateur')], default='etudiant', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_recharge', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.etudiant')),
                ('vendeur', models.ForeignKey(limit_choices_to={'profil__role': 'vendeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
