# Generated by Django 4.2 on 2026-05-30 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debiter',
            name='controleur',
        ),
        migrations.RemoveField(
            model_name='debiter',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendre',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='vendre',
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('caissier', 'Caissier'), ('controleur', 'Contrôleur'), ('admin', 'Administrateur')], default='etudiant', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Achat',
        ),
        migrations.DeleteModel(
            name='Debiter',
        ),
        migrations.DeleteModel(
            name='Depense',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Vendre',
        ),
    ]
