# Generated by Django 4.2 on 2026-05-30 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_remove_debiter_controleur_remove_debiter_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cni', models.CharField(max_length=50, unique=True, verbose_name='CNI')),
                ('numero_ce', models.CharField(max_length=50, unique=True, verbose_name='Carte étudiant')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('niveau', models.CharField(max_length=50)),
                ('filiere', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('wallet', models.IntegerField(default=0)),
                ('tickets_petit_dej', models.IntegerField(default=0)),
                ('tickets_repas', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('vendeur', 'Caissier/Vendeur'), ('controleur', 'Contrôleur'), ('admin', 'Administrateur')], max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('petit_dej', 'Petit déj'), ('repas', 'Repas')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('montant', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.etudiant')),
                ('vendeur', models.ForeignKey(limit_choices_to={'role': 'vendeur'}, on_delete=django.db.models.deletion.CASCADE, to='tickets.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('type_ticket', models.CharField(choices=[('petit_dej', 'Petit déj'), ('repas', 'Repas')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('petit_dej', 'Petit déj'), ('repas', 'Repas')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('controleur', models.ForeignKey(limit_choices_to={'role': 'controleur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.personnel')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='tickets.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('petit_dej', 'Petit déjeuner'), ('repas', 'Repas')], max_length=20)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_total', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paye_par_wave', models.BooleanField(default=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='tickets.etudiant')),
            ],
        ),
    ]
