# Generated by Django 4.2 on 2026-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_etudiant_personnel_vente_qrcode_depense_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('vendeur', 'Caissier/Vendeur'), ('controleur', 'Contrôleur'), ('admin', 'Administrateur')], default='etudiant', max_length=20),
        ),
    ]
