# Generated by Django 4.2 on 2026-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_profilutilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dejeuner', 'Déjeuner (11h30 – 14h)'), ('diner', 'Dîner (18h – 20h)')], max_length=20)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.IntegerField(default=200)),
                ('image_url', models.URLField(blank=True, help_text="URL de l'image du plat", null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'ordering': ['type', 'ordre'],
            },
        ),
    ]
