# Generated by Django 4.2 on 2026-06-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
